
create table if not exists equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  condition text not null,
  quantity int not null check (quantity >= 1),
  available int not null check (available >= 0),
  created_at timestamptz not null default now()
);

create table if not exists loans (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references equipment(id) on delete cascade,
  borrower_name text not null,
  borrowed_at timestamptz not null default now(),
  due_date timestamptz not null,
  returned_at timestamptz
);

create table if not exists waitlist (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references equipment(id) on delete cascade,
  borrower_name text not null,
  days int not null,
  created_at timestamptz not null default now()
);
